### ISSUE TITLE
RuntimeError: Error while importing "env"."abort": unknown import.

### ISSUE THREAD

**Issue by amotl** [flow-heater/hello-pyts#1]
Hi.

Currently, when invoking the wat code coming from TypeScript/AssemblyScript, the program croaks.
```
$ python kernel/core.py typescript

Traceback (most recent call last):
  File "kernel/core.py", line 74, in <module>
    main()
  File "kernel/core.py", line 70, in main
    run_code(code)
  File "kernel/core.py", line 52, in run_code
    instance = Instance(module)
RuntimeError: Error while importing "env"."abort": unknown import. Expected Function(FunctionType { params: [I32, I32, I32, I32], results: [] })
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
The host might have to provide an `abort` function here unless https://github.com/AssemblyScript/assemblyscript/issues/1562 will happen?

If so, in order to implement that, https://github.com/wasmerio/wasmer-python/issues/28 and https://github.com/wasmerio/wasmer-python/issues/106 might be related. It looks like https://github.com/wasmerio/wasmer-python/pull/140 might have solved that already.

An example to use imported functions, aka. host functions, is [`examples/imports_function.py`](https://github.com/wasmerio/wasmer-python/blob/1.0.0-beta1/examples/imports_function.py).

**Comment by amotl** [comment]
With 09deec2, the host now provides an `abort()` function to the Wasm module.
